### ISSUE TITLE
set modloader to forge.

### ISSUE THREAD

**Issue by DeRp-MaSte5** [Bletch1971/TektopiaThief#2]
hey the only reason why i care about the modloader set to forge on the website is that for systems that detect forge or fabric mods for servers, like aternos, won't let your mod in. infact all your tektopia except the info have the same issue.

**Comment by Bletch1971** [comment]
I have updated all my mods to include the modloader. Are you able to confirm that this change fixed the issue?

**Comment by DeRp-MaSte5** [comment]
yes, this fixed the issue. the mods not popular enough for aternos but I think a few more downloads to them and they will be addable to aternos. this might increase the amount of downloads. thank you very much!
